### PR TITLE
Add newly added Button component

### PR DESCRIPTION
**Pull request by pgom**
This PR addes the support for the newly added [Button](https://facebook.github.io/react-native/docs/button.html) component.

### CODE REVIEW

**Review by RealOrangeOne — CHANGES_REQUESTED** [review]
You seem to have comitted the build directory, somehow. Please fix

**Comment by pgom** [comment]
Yeps, @RealOrangeOne. I commited by mistake. Fixed now.

**Comment by pgom** [comment]
BTW, @RealOrangeOne, I'm getting issues when upgrading to `React@15.4.0`. Any plans to upgrade this as well?

**Comment by RealOrangeOne** [comment]
Not unless react-native supports it. We only maintain support for the most recent version

**Review by RealOrangeOne — APPROVED** [review]

**Pull request merged**
