### PR TITLE
Upgrade to RN26 and React 15

### LINKED ISSUE #42: is this work with RN25/RN26 and react 15?

### PR DESCRIPTION
**Pull request by sibelius**
deprecate
[react-addons-clone-with-props](https://facebook.github.io/react/docs/clone-with-props.html)
upgrade deps

fix lelandrichardson/react-native-mock#42

### CODE REVIEW

**Comment by mroswald** [comment]
Please wait until 0.26 is stable. You can't force to upgrade all people to a release candidate :-)

**Comment by chirag04** [comment]
even if 0.26 is stable, this is a breaking change and will break for everyone who is not using 0.26.  

We can do a major bump and not block anyone. @lelandrichardson thoughts?

**Comment by sibelius** [comment]
I think this should be a major

**Comment by omeid** [comment]
It is stable now. Bump please?

**Comment by devhyunjae** [comment]
Having this error too, update plz.

**Comment by andrey-skl** [comment]
react-native 0.26 is stable now so I can't run tests on it because of this issue

**Comment by sibelius** [comment]
I will update the PR with 0.26 stable

**Comment by andrey-skl** [comment]
Guys is there anything we can do to make this merged?

**Comment by lelandrichardson** [comment]
Sorry for the slow response on this. I'm currently on PTO and internet connection is spotty. I've just published this as v0.2.0

Thanks again! If anyone is interested in becoming a collaborator on this project, email me and I'll set it up. I don't want me to be the limiting factor here!

**Comment by chirag04** [comment]
@lelandrichardson This is also a blocker: https://github.com/lelandrichardson/react-native-mock/pull/45

Enjoy :)

**Comment by omeid** [comment]
@lelandrichardson Thanks for following up on this in your time-off!

**Pull request merged**
