### PR TITLE
adds babel transform runtime

### PR DESCRIPTION
**Pull request by bdougie**
In reference to my open issue #27:

 Even when setting my circle.yml similar to how Iset the travis.yml in the #29 pull request.

I however have figured out a solution to get the build to pass on CircleCI and its [babel-runtime](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-runtime). The `new Map()` is unknown in CircleCI's node version, but adding `babel-runtime` overcomes that.

Please let me know if you have any questions

### CODE REVIEW

**Comment by RealOrangeOne** [comment]
> is unknown in CircleCI's node version

If this is infact true (which would surprise me), have you tried with different node versions?

**Comment by bdougie** [comment]
Yes, I tried 5.4.1, 4.0.0, and 4.1.0.

But I just tried 5.0.0 and it works on CircleCI fine. Since this is probably only specific to me #27 is actually resovled without this PR, I will go ahead and close this unless @RealOrangeOne or @lelandrichardson sees any value for adding another babel dependency.

Thanks for the comment RealOrangeOne

I will also close my issue as well.

My Solution:

```
// circle.yml
machine:
  node:
    version: 5.0.0
```

**Comment by RealOrangeOne** [comment]
That does seem weird that it only works on that specific version of Node, and not the later one. Definitely something that should be experimented with before we do something like this.

**Comment by bdougie** [comment]
Yeah it could be an oversight on my part. I can play around with this and research it on my end, but I have a feeling this has nothing to do with this project.

**Comment by bdougie** [comment]
Just a quick update. I updated to react-native 0.23 and no longer need babel-runtime in my project to get all this passing.

Just a hunch but I think its because changes in this commit why babel-runtime is not needed. 

https://github.com/facebook/react-native/commit/9d09efdd53017877328a9fbaef2fd2cfd31352fc 

Anywho, thank you for this project

**Pull request closed without merging**
