### PR TITLE
Callback should be an optional parameter

### PR DESCRIPTION
**Pull request by cgreening**
Not sure what the cleanest way of fixing this is, but callback should be an optional parameter.

### CODE REVIEW

**Comment by xxsnakerxx** [comment]
@cgreening It's great, but we still need to handle rejection of the promise...

I think we can just to pass callback to the `wrap` function with ES6 default parameter...

``` javascript
const wrap = (value, callback = () => {}) => Promise.resolve(value).then(
  obj => callback(null, obj),
  err => callback(err)
);
```

May I ask you to do these changes and update the PR?

**Comment by p16** [comment]
Given there is no activity on this PR I've open https://github.com/lelandrichardson/react-native-mock/pull/35 /cc @cgreening @xxsnakerxx

**Comment by RealOrangeOne** [comment]
@p16 would you say this PR is null now after #35 was merged? If so I can close it.

**Comment by p16** [comment]
@RealOrangeOne yes, I think so 👍

**Comment by RealOrangeOne** [comment]
Closing PR - Old version of already-merged #35

**Pull request closed without merging**
