### PR TITLE
Add mocked TabBarIOS.Item

### PR DESCRIPTION
**Pull request by rmhartog**
Addition of the TabBarIOS.Item subcomponent. Please let me know if you'd prefer a separate file.

### CODE REVIEW

**Comment by lelandrichardson** [comment]
Looks good enough to me for now! Thanks.

**Comment by bob-carson** [comment]
Hey guys, I get the following error when using a `TabBarIOS` in my JSX
> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.  Check the render method of \<my-component>

In trying to fix it, it's unclear to me what usage this is working for.  Do either of you 2 (@rmhartog or @lelandrichardson) know of an example usage of this component that works or did work?  Thanks.

**Comment by RealOrangeOne** [comment]
@bob-carson Looks like there's an issue rendering TabBarIOS in the way it is. This is possibly because of how this PR set up 'TabBarIOS.item'. Not sure how this hasnt been an issue before

**Comment by bob-carson** [comment]
I got you @RealOrangeOne https://github.com/RealOrangeOne/react-native-mock/pull/121

**Pull request merged**
