### PR TITLE
fix propType warning from react 15.3.0

### LINKED ISSUE #91: PropType warnings with RN 0.32.0
I've recently upgraded to RN 0.32.0 and now I'm getting warnings in all my tests.

e.g.

```
...

Warning: You are manually calling a React.PropTypes validation function for the `style` prop on `View`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

Warning: You are manually calling a React.PropTypes validation function for the `transformMatrix` prop on `View`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

...
```

After reading the link they provided (https://fb.me/react-warning-dont-call-proptypes) and looking at some code, it seems like the way styles and transforms are done do violate their new rules. I'm not sure how to best fix it.

Any ideas?

### PR DESCRIPTION
**Pull request by evollu**
fix #91

### CODE REVIEW

**Comment by RealOrangeOne** [comment]
Does this really fix the problem? I'm still seeing a direct call?

**Comment by evollu** [comment]
from official document
https://facebook.github.io/react/warnings/dont-call-proptypes.html#fixing-the-false-positive-in-third-party-proptypes

**Comment by dlahyani** [comment]
@RealOrangeOne  this LGTM, as @evollu  mentioned this is the suggested fix by Facebook.

We would love to see this merged soon.
This is crucial for working with RN 0.33 and, RN 0.33 is required for building with Xcode 8.
LMK if I can help somehow to push this.

Thanks.

**Comment by RealOrangeOne** [comment]
Looking at that documentation, looks fine to me. Merging

**Comment by dlahyani** [comment]
Thanks guys.
What's the process for publishing a new version to npm?

**Comment by RealOrangeOne** [comment]
very much manual, and usually only when theres a couple of changes. Hopefully i'll do a release early next week

**Pull request merged**
