### PR TITLE
Add other Path methods to ART Path mock

### PR DESCRIPTION
**Pull request by viceversus**
This PR resolves issue #100 . It just adds the rest of the ART Path methods to the mock.

### CODE REVIEW

**Review by RealOrangeOne — CHANGES_REQUESTED** [review]
I'm not really a big fan of all this duplication in the functions. Could you add something to dynamically generate the functions given an array of names? Should reduce the amount of duplicate code

**Comment by viceversus** [comment]
Sure, i'll get another PR up soon.

**Comment by viceversus** [comment]
@RealOrangeOne - removed the method duplication

**Review by RealOrangeOne — APPROVED** [review]
Perfect!

**Pull request merged**
